#### The gradient tape in TensorFlow

In [1]:
import tensorflow as tf
x = tf.Variable(5.)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [2]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [3]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=13.0>

In [4]:
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [5]:
x = tf.Variable(tf.random.uniform((2, 2)))
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [6]:
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.56578517, 0.5211791 ],
       [0.78022456, 0.22388434]], dtype=float32)>

In [7]:
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.1315703, 4.0423584],
       [4.560449 , 3.4477687]], dtype=float32)>

In [8]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

**Autre exemple : fonction carré**

In [9]:
x = tf.Variable(3.)
with tf.GradientTape() as tape:
    y = x**2
grad_of_y_wrt_x = tape.gradient(y, x)

In [10]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [11]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [12]:
grad_of_y_wrt_x 

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [13]:
x = tf.Variable([3., 4.])
with tf.GradientTape() as tape:
    y = x**2
grad_of_y_wrt_x = tape.gradient(y, x)

In [14]:
x

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [15]:
y

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 9., 16.], dtype=float32)>

In [16]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6., 8.], dtype=float32)>

In [17]:
x = tf.Variable([2., 3.])
y = tf.Variable([4., 5.])
with tf.GradientTape() as tape:
    z = x**2 + y**2
grad_of_z_wrt_x_and_y = tape.gradient(z, [x, y])

In [18]:
z

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([20., 34.], dtype=float32)>

In [19]:
grad_of_z_wrt_x_and_y

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 6.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 8., 10.], dtype=float32)>]

In [20]:
x = tf.Variable([3., 4.])
with tf.GradientTape() as tape:
    y = x[0]**2 + 4 * x[1]**2
grad_of_y_wrt_x = tape.gradient(y, x)

In [21]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=73.0>

In [22]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 32.], dtype=float32)>

In [54]:
x = tf.Variable([1., 2.])
with tf.GradientTape() as tape:
    y = tf.convert_to_tensor([ x[0]**2 + x[1]**2, x[0]**2 + 2 * x[1]**2 , x[0]**2 + 3 * x[1]**2 ])
grad_of_y_wrt_x = tape.gradient(y, x)

In [55]:
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 5.,  9., 13.], dtype=float32)>

In [56]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 24.], dtype=float32)>

In [51]:
x = tf.Variable([3., 4.])
with tf.GradientTape() as tape:
    y = x[0] * x[1]
grad_of_y_wrt_x = tape.gradient(y, x)

In [52]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [53]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 3.], dtype=float32)>

**Exemple avec une fonction qui renvoie un tenseur 3 x 1**

In [59]:
W = tf.Variable(tf.random.uniform((1, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.constant([[2.], [3.], [4.]])
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [60]:
W

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0.70159316, 0.05504537]], dtype=float32)>

In [61]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [62]:
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[2.],
       [3.],
       [4.]], dtype=float32)>

In [63]:
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.4031863 , 0.11009073],
       [2.1047795 , 0.1651361 ],
       [2.8063726 , 0.22018147]], dtype=float32)>

In [64]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[9., 9.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 3.], dtype=float32)>]

On constate que les valeurs obtenues sont la somme pour les éléments du tenseur ``y``.

In [65]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [66]:
W

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.49113345, 0.42215574],
       [0.08789217, 0.7436031 ]], dtype=float32)>

In [67]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [68]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.8952073 , 0.7273109 ],
       [0.01199651, 0.20803571]], dtype=float32)>

In [69]:
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5035912 , 0.91874754],
       [0.0241766 , 0.1597604 ]], dtype=float32)>

In [70]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.9072038, 0.9072038],
        [0.9353466, 0.9353466]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]